backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "src/index.md"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "Artists", name: "artists", widget: "text" }
          - { label: "Location", name: "location", widget: "text" }
          - { label: "Instagram URL", name: "instagram_url", widget: "string" }
          - { label: "Telegram URL", name: "telegram_url", widget: "string" }
